### ISSUE TITLE
Profile b2iseac

### ISSUE THREAD

**Issue by alastairUK** [eeveetza/p2001#3]
If you look at the Profile4 there is agreement between the last point in the profile definition and the value of Dgc calculated (88.891). 

This is not the case for b2iseac where the profile length is 235.1 and Dgc calculated is 234.50. 

I think it would therefore make more sense to adjust the Lat/Lng of the Rx point to align with the path length. 

I **_think_** the following gives the right path length (maintaining the same bearing from Tx->Rx): 

54.16906634, -3.175115395

**Comment by eeveetza** [comment]
Double checked the proposed new Rx Lat/Lon and it better corresponds to the profile length.
The correction will be introduced to the b2iseac profile and validation results.

**Comment by alastairUK** [comment]
Thanks!
