### ISSUE TITLE
Profile4

### ISSUE THREAD

**Issue by alastairUK** [eeveetza/p2001#4]
Looking at the latest code in the Dev branch there's a couple of issues:

1. testprof4.m is missing the line:

![image](https://user-images.githubusercontent.com/5337814/155364542-3de09a86-bbe8-486c-9465-bb538c9978a1.png)

2. In Validation_examples_ITU-R_P_2001_prof4_profile.csv it looks like the wrong profile info is being used (this looks like a C+P from the other profile)

**Comment by eeveetza** [comment]
Both issues (the missing line and the wrong profile data) are corrected in the provided [patch](https://github.com/eeveetza/p2001/commit/801aeb60aafa24f95c9efed16ae68645d6d986b7).

**Comment by alastairUK** [comment]
👍
